name: Trigger dbt Cloud Job

on:
  push:
    branches:
      - main

jobs:
  trigger-dbt-job:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger dbt Cloud Job
        uses: fjogeleit/http-request-action@master
        with:
          url: 'https://cloud.getdbt.com/api/v2/accounts/255245/jobs/567667/run/'
          method: 'POST'
          contentType: 'application/json'
          headers: '{"Authorization": "Token ${{ secrets.DBT_CLOUD_API_TOKEN }}"}'
